apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-cr-dhcp
spec:
  # we can remove "master" key for not specified of any host interfaces
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "mode": "bridge",
    "master": "enp7s0f0",
    "ipam": {
      "type": "dhcp",
      "daemonSocketPath": "/run/cni/dhcp.sock",
      "request": [{
        "skipDefault": false
      }],
      "provide": [{
        "option": "host-name",
        "fromArg": "K8S_POD_NAME"
      }]
    }
  }'
