apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-mlnx-noipam
  annotations:
    k8s.v1.cni.cncf.io/resourceName: "mellanox.com/mlnx_sriov"
spec:
  config: '{
    "type": "sriov",
    "cniVersion": "0.3.1",
    "name": "sriov-network",
  }'
